dataset:
  train:
    affine: True
    morphology: False
  val:
    affine: False
    morphology: False
  test:
    affine: False
    morphology: False

data:
  train_df_path: input/bengaliai-cv19/train.csv
  train_images_path: input/bengaliai-cv19/train_images
  test_images_path: input/bengaliai-cv19/test_images
  sample_submission_path: input/bengaliai-cv19/sample_submission.csv

model:
  model_name: se_resnext50_32x4d
  pretrained:
  num_classes: 186
  head: custom
  in_channels: 3
  outputs:
    - grapheme
    - vowel
    - consonant

train:
  batch_size: 64
  num_epochs: 90

test:
  batch_size: 128

loss:
  name: ohem
  params:
    n_grapheme: 168
    n_vowel: 11
    n_consonant: 7
    weights:
      - 2.0
      - 1.0
      - 1.0

optimizer:
  name: Adam
  params:
    lr: 0.00005

scheduler:
  name: cosine
  params:
    T_max: 10

transforms:
  train:
    Noise: False
    Contrast: False
    Rotate: True
    RandomScale: True
    Cutout:
      num_holes: 0
  val:
    Noise: False
    Contrast: False
    Rotate: False
    RandomScale: False
    Cutout:
      num_holes: 0
  test:
    Noise: False
    Contrast: False
    Rotate: False
    RandomScale: False
    Cutout:
      num_holes: 0

val:
  name: no_fold
  params:

callbacks:
  - MixupOrCutmixCallback:
      mixup_prob: 0.5
      cutmix_prob: 0.0
      no_aug_epochs: 6

log_dir: log/
num_workers: 2
seed: 1213
img_size: 236
weights:
